EcomProject/EcomProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('store/',include('store.urls')),
    path('cart/',include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('', include('paypal.standard.ipn.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

EcomProject/carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.cart,name="cart"),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
]

EcomProject/orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('add_address_checkout', views.add_address_checkout, name='add_address_checkout'),

    path('coupon/<int:order_id>/', views.coupon, name='coupon'),
    path('apply_coupon/<int:order_id>/', views.apply_coupon, name='apply_coupon'),

    path('place_order/', views.place_order, name='place_order'),
    path('make_payments/<int:order_id>/', views.make_payments, name='make_payments'),
    path('order_confirmation/<int:order_id>/', views.order_confirmation, name='order_confirmation'),

    path('paypal_payment_success/<int:order_id>/', views.paypal_payment_success, name='paypal_payment_success'),
    path('paypal_payment_failed/<int:order_id>/', views.paypal_payment_failed, name='paypal_payment_failed'),

    path('order_detail_admin/<int:order_id>/', views.order_detail_admin, name='order_detail_admin'),

    path('sales_report/', views.sales_report, name='sales_report'),
    path('weekly_sales_report/', views.weekly_sales_report, name='weekly_sales_report'),
    path('monthly_sales_report/', views.monthly_sales_report, name='monthly_sales_report'),
    path('yearly_sales_report/', views.yearly_sales_report, name='yearly_sales_report'),

    path('sales_report_pdf/', views.sales_report_pdf, name='sales_report_pdf'),
    path('weekly_report_pdf/', views.weekly_report_pdf, name='weekly_report_pdf'),
    path('monthly_report_pdf/', views.monthly_report_pdf, name='monthly_report_pdf'),
    path('yearly_report_pdf/', views.yearly_report_pdf, name='yearly_report_pdf'),

]

EcomProject/templates/sales-report/daily-sales-report.html
{% extends 'admin/base_admin.html' %}
{% block title %}
Sales Report
{% endblock title %}

{% block custom_css %}
{% endblock custom_css %}

{% block page_title %}
Sales Report
{% endblock page_title %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
    <div class="container">
        <div class="row">
            {% include 'includes/sidebar-admin-dashboard.html' %}
            <main class="col-md-10">
                <div class="row">
                    <div class="m-2 table-heading text-center font-weight-bold border-bottom bg-info"
                         style="font-size: 24px; line-height: 1.5;">Sales Report
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-3 card text-white bg-success m-2" style="max-width: 8rem;">
                        <div class="card-body text-center">
                            <a href="{% url 'orders:sales_report' %}" class="text-white font-weight-bold"
                               style="font-size: 14px; line-height: 1.5;">Today</a>
                        </div>
                    </div>
                    <div class="col-md-3 card text-white bg-success m-2" style="max-width: 8rem;">
                        <div class="card-body text-center">
                            <a href="{% url 'orders:weekly_sales_report' %}" class="text-white font-weight-bold"
                               style="font-size: 14px; line-height: 1.5;">Weekly</a>
                        </div>
                    </div>
                    <div class="col-md-3 card text-white bg-success m-2" style="max-width: 8rem;">
                        <div class="card-body text-center">
                            <a href="{% url 'orders:monthly_sales_report' %}" class="text-white font-weight-bold"
                               style="font-size: 14px; line-height: 1.5;">Monthly</a>
                        </div>
                    </div>
                    <div class="col-md-3 card text-white bg-success m-2" style="max-width: 8rem;">
                        <div class="card-body text-center">
                            <a href="{% url 'orders:yearly_sales_report' %}" class="text-white font-weight-bold"
                               style="font-size: 14px; line-height: 1.5;">Yearly</a>
                        </div>
                    </div>
                    <div class="col-md-3 card text-white bg-success m-2" style="max-width: 8rem;">
                        <div class="card-body text-center">
                            <a href="" class="text-white font-weight-bold" style="font-size: 14px; line-height: 1.5;">Custom</a>
                        </div>
                    </div>
                </div>
                <div class="row">
                    {% with current_date|date:"Y-m-d" as formatted_day %}
                    <div class="m-2 table-heading text-center text-white font-weight-bold border-bottom bg-secondary"
                         style="font-size: 24px; line-height: 1.5;">Today's Sales ({{ formatted_day }})
                    </div>
                    {% endwith %}
                    <div class="text-right">
                        <a href="{% url 'orders:sales_report_pdf' %}" class="text-white font-weight-bold btn btn-sm btn-primary"
                           style="font-size: 18px; line-height: 1.5;">Download Pdf</a>
                    </div>
                    <div class="m-2">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <td class="table-heading text-center font-weight-bold bg-primary text-white border-bottom mb-3"
                                    style="border: 1px solid #ddd;">
                                    <label>Sl. No.</label>
                                </td>
                                <td class="table-heading text-center font-weight-bold bg-primary text-white border-bottom mb-3"
                                    style="border: 1px solid #ddd;">
                                    <label>Order Number</label>
                                </td>
                                <td class="table-heading text-center font-weight-bold bg-primary text-white border-bottom mb-3"
                                    style="border: 1px solid #ddd;">
                                    <label>Order Amount</label>
                                </td>
                                <td class="table-heading text-center font-weight-bold bg-primary text-white border-bottom mb-3"
                                    style="border: 1px solid #ddd;">
                                    <label>Amount Received</label>
                                </td>
                                <td class="table-heading text-center font-weight-bold bg-primary text-white border-bottom mb-3"
                                    style="border: 1px solid #ddd;">
                                    <label>Payment Status</label>
                                </td>
                            </tr>
                            </thead>
                            <tbody>
                            {% for order in orders %}
                            <tr>
                                <td class="text-center" style="border: 1px solid #ddd;">
                                    <p class="title mb-0"> {{ forloop.counter }} </p>
                                </td>
                                <td class="text-center" style="border: 1px solid #ddd;">
                                    <p class="title mb-0"><a
                                            href="{% url 'orders:order_detail_admin' order.order_number %}">
                                        {{ order.order_number }} </a></p>
                                </td>
                                <td class="text-center" style="border: 1px solid #ddd;">
                                    <p class="title mb-0"> {{ order.order_total | floatformat:2 }} </p>
                                </td>
                                <td class="text-center" style="border: 1px solid #ddd;">
                                    <p class="title mb-0"> {{ order.payment.amount_paid | floatformat:2 }} </p>
                                </td>
                                <td class="text-center" style="border: 1px solid #ddd;">
                                    <p class="title mb-0"> {{ order.payment.status }} </p>
                                </td>
                            </tr>
                            {% endfor %}
                            <tr>
                                <th colspan="2" class="text-right bg-primary text-white"
                                    style="border: 1px solid #ddd;">Grand Total:
                                </th>
                                <th class="text-center bg-primary text-white" style="border: 1px solid #ddd;">
                                    {{ total_order_amount | floatformat:2 }}
                                </th>
                                <th class="text-center bg-primary text-white" style="border: 1px solid #ddd;">
                                    {{ total_amount_paid | floatformat:2 }}
                                </th>
                                <th class="text-center bg-primary text-white" style="border: 1px solid #ddd;"></th>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </main>
        </div> <!-- row.// -->
    </div>
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock%}

{% block custom_js %}


{% endblock custom_js %}

EcomProject/templates/sales-report/monthly-sales-report.html
{% extends 'admin/base_admin.html' %}
{% block title %}
Sales Report
{% endblock title %}

{% block custom_css %}
{% endblock custom_css %}

{% block page_title %}
Sales Report
{% endblock page_title %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
    <div class="container">
        <div class="row">
            {% include 'includes/sidebar-admin-dashboard.html' %}
            <main class="col-md-10">
                <div class="row">
                    <div class="m-2 table-heading text-center font-weight-bold border-bottom bg-info"
                                 style="font-size: 24px; line-height: 1.5;">Sales Report
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-3 card text-white bg-success m-2" style="max-width: 8rem;">
                      <div class="card-body text-center">
                        <a href="{% url 'orders:sales_report' %}" class="text-white font-weight-bold" style="font-size: 14px; line-height: 1.5;">Today</a>
                      </div>
                    </div>
                    <div class="col-md-3 card text-white bg-success m-2" style="max-width: 8rem;">
                      <div class="card-body text-center">
                        <a href="{% url 'orders:weekly_sales_report' %}" class="text-white font-weight-bold" style="font-size: 14px; line-height: 1.5;">Weekly</a>
                      </div>
                    </div>
                    <div class="col-md-3 card text-white bg-success m-2" style="max-width: 8rem;">
                      <div class="card-body text-center">
                        <a href="{% url 'orders:monthly_sales_report' %}" class="text-white font-weight-bold" style="font-size: 14px; line-height: 1.5;">Monthly</a>
                      </div>
                    </div>
                    <div class="col-md-3 card text-white bg-success m-2" style="max-width: 8rem;">
                      <div class="card-body text-center">
                        <a href="{% url 'orders:yearly_sales_report' %}" class="text-white font-weight-bold" style="font-size: 14px; line-height: 1.5;">Yearly</a>
                      </div>
                    </div>
                    <div class="col-md-3 card text-white bg-success m-2" style="max-width: 8rem;">
                      <div class="card-body text-center">
                        <a href="" class="text-white font-weight-bold" style="font-size: 14px; line-height: 1.5;">Custom</a>
                      </div>
                    </div>
                </div>
                <div class="row">
                    {% load tz %} {# Load the timezone template tags #}
                    {% with start_of_month|date:"Y-m-d" as formatted_start %}
                        {% with end_of_month|date:"Y-m-d" as formatted_end %}
                            <div class="m-2 table-heading text-center text-white font-weight-bold border-bottom bg-secondary"
                                 style="font-size: 24px; line-height: 1.5;">
                                Monthly Sales Report ({{ formatted_start }} - {{ formatted_end }})
                            </div>
                        {% endwith %}
                    {% endwith %}
                    <div class="text-right">
                        <a href="{% url 'orders:monthly_report_pdf' %}" class="text-white font-weight-bold btn btn-sm btn-primary"
                           style="font-size: 18px; line-height: 1.5;">Download Pdf</a>
                    </div>
                    <div class="m-2">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <td class="table-heading text-center font-weight-bold bg-primary text-white border-bottom mb-3">
                                        <label>Sl. No.</label>
                                    </td>
                                    <td class="table-heading text-center font-weight-bold bg-primary text-white border-bottom mb-3">
                                        <label>Order Date</label>
                                    </td>
                                    <td class="table-heading text-center font-weight-bold bg-primary text-white border-bottom mb-3">
                                        <label>Order Number</label>
                                    </td>
                                    <td class="table-heading text-center font-weight-bold bg-primary text-white border-bottom mb-3">
                                        <label>Order Amount</label>
                                    </td>
                                    <td class="table-heading text-center font-weight-bold bg-primary text-white border-bottom mb-3">
                                        <label>Amount Paid</label>
                                    </td>
                                    <td class="table-heading text-center font-weight-bold bg-primary text-white border-bottom mb-3">
                                        <label>Payment Status</label>
                                    </td>
                                </tr>
                            </thead>
                            <tbody>
                            {% for order in orders %}
                                <tr>
                                    <td class="text-center" style="border: 1px solid #ddd;">
                                        <p class="title mb-0"> {{ forloop.counter }} </p>
                                    </td>
                                    {% with order.created_at|date:"Y-m-d" as formatted_created_at %}
                                    <td class="text-center" style="border: 1px solid #ddd;">
                                        <p class="title mb-0"> {{ formatted_created_at }} </p>
                                    </td>
                                    {% endwith %}
                                    <td class="text-center" style="border: 1px solid #ddd;">
                                        <p class="title mb-0"> <a href="{% url 'orders:order_detail_admin' order.order_number %}"> {{ order.order_number }} </a></p>
                                    </td>
                                    <td class="text-center" style="border: 1px solid #ddd;">
                                        <p class="title mb-0"> {{ order.order_total | floatformat:2 }} </p>
                                    </td>
                                    <td class="text-center" style="border: 1px solid #ddd;">
                                        <p class="title mb-0"> {{ order.payment.amount_paid | floatformat:2 }} </p>
                                    </td>
                                    <td class="text-center" style="border: 1px solid #ddd;">
                                        <p class="title mb-0"> {{ order.payment.status }} </p>
                                    </td>
                                </tr>
                            {% endfor %}
                                <tr>
                                    <th colspan="3" class="text-right bg-primary text-white" style="border: 1px solid #ddd;">Grand Total:</th>
                                    <th class="text-center bg-primary text-white" style="border: 1px solid #ddd;"> {{ total_order_amount|floatformat:2 }}</th>
                                    <th class="text-center bg-primary text-white" style="border: 1px solid #ddd;"> {{ total_amount_paid|floatformat:2 }}</th>
                                    <th class="text-center bg-primary text-white" style="border: 1px solid #ddd;"></th>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </main>
        </div> <!-- row.// -->
    </div>
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock%}

{% block custom_js %}


{% endblock custom_js %}

EcomProject/templates/sales-report/weekly-sales-report.html
{% extends 'admin/base_admin.html' %}
{% block title %}
Sales Report
{% endblock title %}

{% block custom_css %}
{% endblock custom_css %}

{% block page_title %}
Sales Report
{% endblock page_title %}

{% block content %}

<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y bg">
    <div class="container">
        <div class="row">
            {% include 'includes/sidebar-admin-dashboard.html' %}
            <main class="col-md-10">
                <div class="row">
                    <div class="m-2 table-heading text-center font-weight-bold border-bottom bg-info"
                                 style="font-size: 24px; line-height: 1.5;">Sales Report
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-md-3 card text-white bg-success m-2" style="max-width: 8rem;">
                      <div class="card-body text-center">
                        <a href="{% url 'orders:sales_report' %}" class="text-white font-weight-bold" style="font-size: 14px; line-height: 1.5;">Today</a>
                      </div>
                    </div>
                    <div class="col-md-3 card text-white bg-success m-2" style="max-width: 8rem;">
                      <div class="card-body text-center">
                        <a href="{% url 'orders:weekly_sales_report' %}" class="text-white font-weight-bold" style="font-size: 14px; line-height: 1.5;">Weekly</a>
                      </div>
                    </div>
                    <div class="col-md-3 card text-white bg-success m-2" style="max-width: 8rem;">
                      <div class="card-body text-center">
                        <a href="{% url 'orders:monthly_sales_report' %}" class="text-white font-weight-bold" style="font-size: 14px; line-height: 1.5;">Monthly</a>
                      </div>
                    </div>
                    <div class="col-md-3 card text-white bg-success m-2" style="max-width: 8rem;">
                      <div class="card-body text-center">
                        <a href="{% url 'orders:yearly_sales_report' %}" class="text-white font-weight-bold" style="font-size: 14px; line-height: 1.5;">Yearly</a>
                      </div>
                    </div>
                    <div class="col-md-3 card text-white bg-success m-2" style="max-width: 8rem;">
                      <div class="card-body text-center">
                        <a href="" class="text-white font-weight-bold" style="font-size: 14px; line-height: 1.5;">Custom</a>
                      </div>
                    </div>
                </div>
                <div class="row">
                    {% load tz %} {# Load the timezone template tags #}
                    {% with start_of_week|date:"Y-m-d" as formatted_start %}
                        {% with end_of_week|date:"Y-m-d" as formatted_end %}
                            <div class="m-2 table-heading text-center text-white font-weight-bold border-bottom bg-secondary"
                                 style="font-size: 24px; line-height: 1.5;">
                                Weekly Sales Report ({{ formatted_start }} - {{ formatted_end }})
                            </div>
                        {% endwith %}
                    {% endwith %}
                    <div class="text-right">
                        <a href="{% url 'orders:weekly_report_pdf' %}" class="text-white font-weight-bold btn btn-sm btn-primary"
                           style="font-size: 18px; line-height: 1.5;">Download Pdf</a>
                    </div>
                    <div class="m-2">
                        <table class="table table-hover">
                            <thead>
                                <tr>
                                    <td class="table-heading text-center font-weight-bold bg-primary text-white border-bottom mb-3">
                                        <label>Sl. No.</label>
                                    </td>
                                    <td class="table-heading text-center font-weight-bold bg-primary text-white border-bottom mb-3">
                                        <label>Order Date</label>
                                    </td>
                                    <td class="table-heading text-center font-weight-bold bg-primary text-white border-bottom mb-3">
                                        <label>Order Number</label>
                                    </td>
                                    <td class="table-heading text-center font-weight-bold bg-primary text-white border-bottom mb-3">
                                        <label>Order Amount</label>
                                    </td>
                                    <td class="table-heading text-center font-weight-bold bg-primary text-white border-bottom mb-3">
                                        <label>Amount Paid</label>
                                    </td>
                                    <td class="table-heading text-center font-weight-bold bg-primary text-white border-bottom mb-3">
                                        <label>Payment Status</label>
                                    </td>
                                </tr>
                            </thead>
                            <tbody>
                            {% for order in orders %}
                                <tr>
                                    <td class="text-center" style="border: 1px solid #ddd;">
                                        <p class="title mb-0"> {{ forloop.counter }} </p>
                                    </td>
                                    {% with order.created_at|date:"Y-m-d" as formatted_created_at %}
                                    <td class="text-center" style="border: 1px solid #ddd;">
                                        <p class="title mb-0"> {{ formatted_created_at }} </p>
                                    </td>
                                    {% endwith %}
                                    <td class="text-center" style="border: 1px solid #ddd;">
                                        <p class="title mb-0"> <a href="{% url 'orders:order_detail_admin' order.order_number %}"> {{ order.order_number }} </a></p>
                                    </td>
                                    <td class="text-center" style="border: 1px solid #ddd;">
                                        <p class="title mb-0"> {{ order.order_total | floatformat:2 }} </p>
                                    </td>
                                    <td class="text-center" style="border: 1px solid #ddd;">
                                        <p class="title mb-0"> {{ order.payment.amount_paid | floatformat:2 }} </p>
                                    </td>
                                    <td class="text-center" style="border: 1px solid #ddd;">
                                        <p class="title mb-0"> {{ order.payment.status }} </p>
                                    </td>
                                </tr>
                            {% endfor %}
                                <tr>
                                    <th colspan="3" class="text-right bg-primary text-white" style="border: 1px solid #ddd;">Grand Total:</th>
                                    <th class="text-center bg-primary text-white" style="border: 1px solid #ddd;"> {{ total_order_amount | floatformat:2 }}</th>
                                    <th class="text-center bg-primary text-white" style="border: 1px solid #ddd;"> {{ total_amount_paid | floatformat:2 }}</th>
                                    <th class="text-center bg-primary text-white" style="border: 1px solid #ddd;"></th>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </main>
        </div> <!-- row.// -->
    </div>
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock%}

{% block custom_js %}


{% endblock custom_js %}