EcomProject/EcomProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('store/',include('store.urls')),
    path('cart/',include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('', include('paypal.standard.ipn.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

EcomProject/carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.cart,name="cart"),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
]

EcomProject/orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('add_address_checkout', views.add_address_checkout, name='add_address_checkout'),

    path('coupon/<int:order_id>/', views.coupon, name='coupon'),
    path('apply_coupon/<int:order_id>/', views.apply_coupon, name='apply_coupon'),

    path('place_order/', views.place_order, name='place_order'),
    path('make_payments/<int:order_id>/', views.make_payments, name='make_payments'),
    path('order_confirmation/<int:order_id>/', views.order_confirmation, name='order_confirmation'),

    path('paypal_payment_success/<int:order_id>/', views.paypal_payment_success, name='paypal_payment_success'),
    path('paypal_payment_failed/<int:order_id>/', views.paypal_payment_failed, name='paypal_payment_failed'),

    path('order_detail_admin/<int:order_id>/', views.order_detail_admin, name='order_detail_admin'),

    path('sales_report/', views.sales_report, name='sales_report'),
    path('weekly_sales_report/', views.weekly_sales_report, name='weekly_sales_report'),
    path('monthly_sales_report/', views.monthly_sales_report, name='monthly_sales_report'),
    path('yearly_sales_report/', views.yearly_sales_report, name='yearly_sales_report'),

    path('sales_report_pdf/', views.sales_report_pdf, name='sales_report_pdf'),
    path('weekly_report_pdf/', views.weekly_report_pdf, name='weekly_report_pdf'),
    path('monthly_report_pdf/', views.monthly_report_pdf, name='monthly_report_pdf'),
    path('yearly_report_pdf/', views.yearly_report_pdf, name='yearly_report_pdf'),

]

EcomProject/store/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.store, name='store'),
    path('category/<slug:category_slug>/', views.store, name='products_by_category'),
    path('category/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name='product_detail'),
    path('search/', views.search, name='search')
]

EcomProject/store/models.py
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse
from category.models import Category
# Create your models here.

class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(max_length=500, blank=True)
    price = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        help_text="Enter a number greater than zero")
    product_image = models.ImageField(upload_to='photos/products')
    stock = models.PositiveIntegerField(
        validators=[MinValueValidator(1)],
        help_text="Enter a number greater than zero")
    is_available = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    offer_percentage = models.PositiveIntegerField(default=0, blank=True, null=True)
    offer_price = models.PositiveIntegerField(default=0, blank=True, null=True)

    def get_url(self):
        return reverse('product_detail',args=[self.category.slug, self.slug])

    def __str__(self):
        return self.product_name

class VariantManager(models.Manager):
    def colors(self):
        return super(VariantManager, self).filter(variant_category = 'color', is_active = True)

    def sizes(self):
        return super(VariantManager, self).filter(variant_category = 'size', is_active = True)

variant_category_choice = (
    ('color', 'color'),
    ('size', 'size'),
    )

class Variant(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variant_category = models.CharField(max_length=100, choices=variant_category_choice)
    variant_value = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)
    created_on = models.DateTimeField(auto_now=True)

    objects = VariantManager()

    def __str__(self):
        return self.variant_value

EcomProject/carts/views.py
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from store.models import Product, Variant
from .models import Cart, CartItem, UserCoupons, Coupons
from accounts.models import Address
from accounts.forms import AddressForm
from orders.models import Order
from django.contrib.auth.decorators import login_required

from django.http import HttpResponse

# Create your views here.

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def cart(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)

        total_discount = 0

        for cart_item in cart_items:
            if cart_item.product.offer_percentage > 0:
                discount_price = (cart_item.product.offer_percentage * cart_item.product.price) / 100
                total_discount += discount_price * cart_item.quantity
                cart_item.product.offer_price = cart_item.product.price - discount_price
                total += (cart_item.product.offer_price * cart_item.quantity)
                quantity += cart_item.quantity
            else:
                total += (cart_item.product.price * cart_item.quantity)
                quantity += cart_item.quantity
        #Total amount befor discount
        net_total = total + total_discount
        tax = (2 * total)/100
        #Total amount after discount
        grand_total = total + tax

    except ObjectDoesNotExist:
        pass

    context = {
        'net_total' : net_total,
        'total_discount' : total_discount,
        'total' : total,
        'quantity' : quantity,
        'cart_items' : cart_items,
        'tax' : tax,
        'grand_total' : grand_total,
    }
    return render(request, 'store/cart.html', context)

def add_cart(request, product_id):
    current_user = request.user
    product = Product.objects.get(id=product_id)
    # If the user is authenticated:
    if current_user.is_authenticated:
        product_variant = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]
                try:
                    variant = Variant.objects.get(product=product, variant_category__iexact=key,
                                                  variant_value__iexact=value)
                    product_variant.append(variant)
                except:
                    pass
        is_cart_item_exists = CartItem.objects.filter(product=product, user=current_user).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, user=current_user)
            ex_variant_list = []
            id = []
            for item in cart_item:
                existing_variant = item.variant.all()
                ex_variant_list.append(list(existing_variant))
                id.append(item.id)

            if product_variant in ex_variant_list:
                index = ex_variant_list.index(product_variant)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(product=product, quantity=1, user=current_user)
                if len(product_variant) > 0:
                    item.variant.clear()
                    item.variant.add(*product_variant)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                user = current_user,
            )
            if len(product_variant) > 0:
                cart_item.variant.clear()
                for item in product_variant:
                    cart_item.variant.add(item)
            cart_item.save()
        return redirect('cart')
    # If the user is not authenticated:
    else:
        product_variant = []
        if request.method == 'POST':
            for item in request.POST:
                key = item
                value = request.POST[key]
                try:
                    variant = Variant.objects.get(product = product, variant_category__iexact = key, variant_value__iexact = value)
                    product_variant.append(variant)
                except:
                    pass
        try:
            cart = Cart.objects.get(cart_id=_cart_id(request))
        except Cart.DoesNotExist:
            cart = Cart.objects.create(cart_id = _cart_id(request))

        is_cart_item_exists = CartItem.objects.filter(product=product, cart=cart).exists()
        if is_cart_item_exists:
            cart_item = CartItem.objects.filter(product=product, cart=cart)
            ex_variant_list = []
            id = []
            for item in cart_item:
                existing_variant = item.variant.all()
                ex_variant_list.append(list(existing_variant))
                id.append(item.id)

            if product_variant in ex_variant_list:
                index = ex_variant_list.index(product_variant)
                item_id = id[index]
                item = CartItem.objects.get(product=product, id=item_id)
                item.quantity += 1
                item.save()
            else:
                item = CartItem.objects.create(product=product, quantity=1, cart=cart)
                if len(product_variant) > 0:
                    item.variant.clear()
                    item.variant.add(*product_variant)
                item.save()
        else:
            cart_item = CartItem.objects.create(
                product = product,
                quantity = 1,
                cart = cart,
            )
            if len(product_variant) > 0:
                cart_item.variant.clear()
                for item in product_variant:
                    cart_item.variant.add(item)
            cart_item.save()
        return redirect('cart')

def remove_cart(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    try:
        if request.user.is_authenticated:
            cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
        if cart_item.quantity > 1:
            cart_item.quantity -= 1
            cart_item.save()
        else:
            cart_item.delete()
    except:
        pass
    return redirect('cart')

def remove_cart_item(request, product_id, cart_item_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        cart_item = CartItem.objects.get(product=product, user=request.user, id=cart_item_id)
    else:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_item = CartItem.objects.get(product=product, cart=cart, id=cart_item_id)
    cart_item.delete()
    return redirect('cart')

@login_required(login_url='login_user')
def checkout(request, total=0, quantity=0, cart_items=None):
    try:
        tax = 0
        grand_total = 0
        if request.user.is_authenticated:
            cart_items = CartItem.objects.filter(user=request.user, is_active=True)
        else:
            cart = Cart.objects.get(cart_id=_cart_id(request))
            cart_items = CartItem.objects.filter(cart=cart, is_active=True)

        total_discount = 0

        for cart_item in cart_items:
            if cart_item.product.offer_percentage > 0:
                discount_price = (cart_item.product.offer_percentage * cart_item.product.price) / 100
                total_discount += discount_price * cart_item.quantity
                cart_item.product.offer_price = cart_item.product.price - discount_price
                total += (cart_item.product.offer_price * cart_item.quantity)
                quantity += cart_item.quantity
            else:
                total += (cart_item.product.price * cart_item.quantity)
                quantity += cart_item.quantity
        #Total amount befor discount
        net_total = total + total_discount
        tax = (2 * total)/100
        #Total amount after discount
        grand_total = total + tax

    except ObjectDoesNotExist:
        pass

    current_user = request.user
    user_addresses = Address.objects.filter(user=current_user)



    if request.method == 'POST':
        # User selected an existing address
        selected_address_id = request.POST.get('selected_address', None)
        if selected_address_id:
            address = get_object_or_404(Address, id=selected_address_id)
        else:
            messages.error(request, "Please add at least one address before placing an order.")
            return redirect('orders:add_address_checkout')

        # Create the order object and associate it with the selected or new address
        data = Order()
        data.user = current_user
        data.address = address
        data.save()

    context = {
        'net_total': net_total,
        'total': total,
        'total_discount': total_discount,
        'quantity': quantity,
        'cart_items': cart_items,
        'tax': tax,
        'grand_total': grand_total,
        'user_addresses': user_addresses,
    }
    return render(request, 'store/checkout.html', context)

EcomProject/store/views.py
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Product
from category.models import Category
from carts.views import _cart_id
from carts.models import Cart, CartItem
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator


def store(request, category_slug=None):
    categories = None
    products = None


    if category_slug != None:
        categories = get_object_or_404(Category, slug=category_slug)
        products = Product.objects.filter(category=categories, is_available=True)
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()

        for item in products:
            discount_price = (item.offer_percentage * item.price)/100
            item.offer_price = item.price - discount_price
            item.save()

    else:
        products = Product.objects.all().filter(is_available=True).order_by('id')
        paginator = Paginator(products, 6)
        page = request.GET.get('page')
        paged_products = paginator.get_page(page)
        product_count = products.count()

        for item in products:
            discount_price = (item.offer_percentage * item.price)/100
            item.offer_price = item.price - discount_price
            item.save()

    context = {
        'products': paged_products,
        'product_count': product_count,
    }
    return render(request, 'store/store.html', context)


def product_detail(request, category_slug, product_slug):
    try:
        single_product = Product.objects.get(category__slug=category_slug, slug=product_slug)
        discount_price = (single_product.offer_percentage * single_product.price) / 100
        single_product.offer_price = single_product.price - discount_price
        single_product.save()

        in_cart = CartItem.objects.filter(cart__cart_id = _cart_id(request), product = single_product).exists()
    except Exception as e:
        raise e

    context = {
        'single_product': single_product,
        'in_cart' : in_cart,
    }
    return render(request, 'store/product_detail.html', context)

def search(request):
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            products = Product.objects.order_by('-created_date').filter(Q(description__icontains=keyword) | Q(product_name__icontains=keyword))
            product_count = products.count()
    context = {
        'products' : products,
        'product_count' : product_count
    }
    return render(request, 'store/store.html', context)

EcomProject/templates/store/checkout.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="section-content padding-y bg">
    <div class="container">
        <!-- ============================ COMPONENT 1 ================================= -->
        <div class="row">
            <aside class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title mb-4 text-center">Billing Address</h4>
                        <div class="card-body">
                            <a href="{% url 'orders:add_address_checkout' %}" class="btn btn-success"> Add New Address <i
                            class="fas fa-chevron"></i></a>
                        </div>
                        <form action="{% url 'orders:place_order' %}" method="POST">
                            {% csrf_token %}
                            <div class="row form-group">
                                <div class="col-md-12">
                                    <h5 class="text-center text-white bg-warning" style="border-radius: 8px; padding: 5px;">Choose Delivery address:</h5>
                                    <div class="custom-control custom-radio">
                                        {% for address in user_addresses %}
                                            <div>
                                                <input type="radio" id="address{{ address.id }}" name="selected_address" class="custom-control-input" value="{{ address.id }}" required>
                                                <label class="custom-control-label" for="address{{ address.id }}">
                                                {{ address.full_name }} - {{ address.address_line_1 }}, {{ address.city }}
                                            </label>
                                            </div>

                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                    </div>
                </div> <!-- card.// -->
            </aside> <!-- col.// -->

            <aside class="col-lg-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="text-center text-white bg-warning" style="border-radius: 8px; padding: 5px;"> Order Summary </h5>
                        <table class="table table-borderless table-shopping-cart">
                            <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for cart_item in cart_items %}
                            <tr>
                                <td>
                                    <figure class="itemside align-items-center">
                                        <div class="aside"><img src="{{ cart_item.product.product_image.url }}"
                                                                class="img-sm">
                                        </div>
                                        <figcaption class="info">
                                            <a href="{{ cart_item.product.get_url }}" class="title text-dark">
                                                {{ cart_item.product.product_name }}</a>
                                            <p class="text-muted small">
                                                {% if cart_item.variant.all %}
                                                    {% for item in cart_item.variant.all %}
                                                        {{ item.variant_category | capfirst }}: {{ item.variant_value | capfirst }} <br>
                                                    {% endfor %}
                                                {% endif %}
                                            </p>
                                        </figcaption>
                                    </figure>
                                </td>
                                <td>
                                    <label>{{ cart_item.quantity }}</label>
                                </td>
                                <td>
                                    {% if cart_item.product.offer_percentage > 0 %}
                                        <div class="price-wrap">
                                            <var class="price">Rs. {{ cart_item.sub_total_offer }} </var>
                                            <small class="text-muted"> Rs. {{ cart_item.product.offer_price }} each </small>
                                        </div> <!-- price-wrap .// -->
                                    {% else %}
                                        <div class="price-wrap">
                                            <var class="price">Rs. {{ cart_item.sub_total }} </var>
                                            <small class="text-muted"> Rs. {{ cart_item.product.price }} each </small>
                                        </div> <!-- price-wrap .// -->
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                            <div class="card col-md-12">
                                <div class="card-body text-center">
                                    <span>Sub Total:</span>
                                    <span class="text-right"><strong>Rs. {{ total | floatformat:2 }}</strong> | </span>
                                    <span>Tax:</span>
                                    <span class="text-right"><strong>Rs. {{ tax | floatformat:2 }}</strong> | </span>
                                    <span>Grand Total:</span>
                                    <span class="text-right"><strong>Rs. {{ grand_total | floatformat:2 }}</strong></span>
                                    {% if total_discount > 0 %}
                                    <hr>
                                     <p class="text-center">You have saved! <strong>Rs. {{ total_discount | floatformat:2 }}</strong></p>
                                    {% endif %}
                                </div> <!-- card-body.// -->
                            </div> <!-- card.// -->
                        <button type="submit" name="submit" class="btn btn-primary btn-block">Proceed to Place Order</button>
                        <a href="{% url 'store' %}" class="btn btn-light btn-block">Continue Shopping</a>
                        </form>
                    </div> <!-- card-body.// -->
                </div> <!-- card.// -->
            </aside> <!-- col.// -->
        </div> <!-- row.// -->
        <!-- ============================ COMPONENT 1 END .// ================================= -->

    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

EcomProject/templates/store/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="section-content padding-y bg">
    <div class="container">
        <!-- ============================ COMPONENT 1 ================================= -->
        <div class="card">
            <div class="row no-gutters">
                <aside class="col-md-6">
                    <article class="gallery-wrap">
                        <div class="img-big-wrap">
                            <a href="#"><img src="{{ single_product.product_image.url }}"></a>
                        </div> <!-- img-big-wrap.// -->

                    </article> <!-- gallery-wrap .end// -->
                </aside>
                <main class="col-md-6 border-left">
                    <form action="{% url 'add_cart' single_product.id %}" method="POST">
                        {% csrf_token %}
                        <article class="content-body">
                            <h2 class="title">{{ single_product.product_name }}</h2>
                            <div class="mb-3">
                                {% if single_product.offer_percentage > 0 %}
                                    <span class="price">{{ single_product.offer_percentage }}% off</span>
                                    <span class="price">Rs. {{ single_product.offer_price }}</span>
                                    <del class="price-old">Rs. {{ single_product.price }}</del>
                                {% else %}
                                    <var class="price h4">Rs. {{ single_product.price }}</var>
                                {% endif %}
                            </div>
                            <p>{{ single_product.description }}</p>
                            <hr>
                            <div class="row">
                                <div class="item-option-select">
                                    <h6>Choose Color</h6>
                                    <select name="color" class="form-control" required>
                                        <option value="" disabled selected>Select</option>
                                        {% for i in single_product.variant_set.colors %}
                                        <option value="{{ i.variant_value | lower }}">{{ i.variant_value | capfirst }}
                                        </option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div> <!-- row.// -->
                            <div class="row">
                                <div class="item-option-select">
                                    <h6>Select Size</h6>
                                    <select name="size" class="form-control" required>
                                        <option value="" disabled selected>Select</option>
                                        {% for i in single_product.variant_set.sizes %}
                                        <option value="{{ i.variant_value | lower }}">{{ i.variant_value | capfirst }}
                                        </option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div> <!-- row.// -->
                            <hr>
                            {% if single_product.stock <= 0 %}
                                <h5 class="text-danger">Out of Stock</h5>
                            {% else %}
                                <button type="submit" class="btn  btn-primary"> <span
                                    class="text">Add to cart</span> <i class="fas fa-shopping-cart"></i></button>
                            {% endif %}
                        </article> <!-- product-info-aside .// -->
                    </form>
                </main> <!-- col.// -->
            </div> <!-- row.// -->
        </div> <!-- card.// -->
        <!-- ============================ COMPONENT END .// ================================= -->
    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->
{% endblock %}