EcomProject/EcomProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('store/',include('store.urls')),
    path('cart/',include('carts.urls')),
    path('accounts/', include('accounts.urls')),
    path('orders/', include('orders.urls')),
    path('', include('paypal.standard.ipn.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

EcomProject/carts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.cart,name="cart"),
    path('add_cart/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove_cart/<int:product_id>/<int:cart_item_id>/', views.remove_cart, name='remove_cart'),
    path('remove_cart_item/<int:product_id>/<int:cart_item_id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
]

EcomProject/orders/urls.py
from django.urls import path
from . import views


app_name = 'orders'

urlpatterns = [
    path('add_address_checkout', views.add_address_checkout, name='add_address_checkout'),

    path('coupon/<int:order_id>/', views.coupon, name='coupon'),
    path('apply_coupon/<int:order_id>/', views.apply_coupon, name='apply_coupon'),

    path('place_order/', views.place_order, name='place_order'),
    path('make_payments/<int:order_id>/', views.make_payments, name='make_payments'),
    path('order_confirmation/<int:order_id>/', views.order_confirmation, name='order_confirmation'),

    path('paypal_payment_success/<int:order_id>/', views.paypal_payment_success, name='paypal_payment_success'),
    path('paypal_payment_failed/<int:order_id>/', views.paypal_payment_failed, name='paypal_payment_failed'),

    path('order_detail_admin/<int:order_id>/', views.order_detail_admin, name='order_detail_admin'),

    path('sales_report/', views.sales_report, name='sales_report'),
    path('weekly_sales_report/', views.weekly_sales_report, name='weekly_sales_report'),
    path('monthly_sales_report/', views.monthly_sales_report, name='monthly_sales_report'),
    path('yearly_sales_report/', views.yearly_sales_report, name='yearly_sales_report'),

    path('sales_report_pdf/', views.sales_report_pdf, name='sales_report_pdf'),
    path('weekly_report_pdf/', views.weekly_report_pdf, name='weekly_report_pdf'),
    path('monthly_report_pdf/', views.monthly_report_pdf, name='monthly_report_pdf'),
    path('yearly_report_pdf/', views.yearly_report_pdf, name='yearly_report_pdf'),

]

EcomProject/orders/models.py
from django.db import models
from accounts.models import Account, Address
from django.utils import timezone
from store.models import Product, Variant

# Create your models here.

class Payment(models.Model):
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    payment_id = models.CharField(max_length=100)
    amount_paid = models.CharField(max_length=100)
    discount = models.FloatField(default=0)
    status = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    timestamp = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.payment_id


class Order(models.Model):
    STATUS = (
        ('Pending', 'Pending'),
        ('Order Confirmed', 'Order Confirmed'),
        ('Return Requested', 'Return Requested'),
        ('Return Approved', 'Return Approved'),
        ('Return Rejected', 'Return Rejected'),
        ('Return Received', 'Return Received'),
        ('Cancelled', 'Cancelled'),
        ('Delivered', 'Delivered'),
    )

    user = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
    address = models.ForeignKey(Address, on_delete=models.SET_NULL, null=True)
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, null=True)
    order_number = models.CharField(max_length=30, unique=True)
    order_total = models.FloatField()
    tax = models.FloatField()
    status = models.CharField(max_length=20, choices=STATUS, default='Pending')
    ip = models.CharField(blank=True, max_length=20)
    is_ordered = models.BooleanField(default=False)
    is_cancelled = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    coupon_discount = models.FloatField(default=0.0)


    def __unicode__(self):
        return self.user.first_name

class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='products')
    payment = models.ForeignKey(Payment, on_delete=models.SET_NULL, blank=True, null=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    variant = models.ManyToManyField(Variant, blank=True)
    quantity = models.IntegerField()
    tax = models.FloatField(default=0.0)
    product_price = models.FloatField()
    ordered = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    product_discount = models.FloatField(default=0.0)

    def __unicode__(self):
        return self.product.prodcut_name

EcomProject/orders/forms.py
from django import forms
from .models import Order


class ChangeStatusForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['status']


class SalesReportForm(forms.Form):
    start_date = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        label='Start Date'
    )
    end_date = forms.DateField(
        widget=forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
        label='End Date'
    )

EcomProject/orders/views.py
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Sum
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.utils import timezone
from .models import Order, OrderProduct, Payment
from carts.models import CartItem
from store.models import Product
import datetime
from datetime import date
from django.contrib import messages
import uuid
from accounts.models import Address
from paypal.standard.forms import PayPalPaymentsForm
from django.urls import reverse
from accounts.forms import AddressForm
from carts.models import Coupons, UserCoupons
from django.http import FileResponse
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter


# Create your views here.

@login_required(login_url='login_user')
def add_address_checkout(request):
    if request.method == 'POST':
        form = AddressForm(request.POST)
        if form.is_valid():
            # Get the current user
            current_user = request.user

            # Extract data from the form
            full_name = form.cleaned_data['full_name']
            phone_number = form.cleaned_data['phone_number']
            address_line_1 = form.cleaned_data['address_line_1']
            address_line_2 = form.cleaned_data['address_line_2']
            city = form.cleaned_data['city']
            state = form.cleaned_data['state']
            country = form.cleaned_data['country']
            zipcode = form.cleaned_data['zipcode']

            # Create and save the address with the current user
            address = Address.objects.create(
                user=current_user,
                full_name=full_name,
                phone_number=phone_number,
                address_line_1=address_line_1,
                address_line_2=address_line_2,
                city=city,
                state=state,
                country=country,
                zipcode=zipcode
            )

            messages.success(request, 'Address Added Successfully.')
            return redirect('checkout')
    else:
        form = AddressForm()

    context = {
        'form': form
    }
    return render(request, 'orders/add-address-checkout.html', context)


def place_order(request, quantity=0, total=0):
    current_user = request.user
    cart_items = CartItem.objects.filter(user=current_user)
    cart_count = cart_items.count()

    if cart_count <= 0:
        return redirect('store')

    user_addresses = Address.objects.filter(user=current_user)
    if not user_addresses:
        messages.error(request, "Please add at least one address before placing an order.")
        return redirect('orders:add_address_checkout')

    for cart_item in cart_items:
        if cart_item.product.offer_percentage > 0:
            discount_price = (cart_item.product.offer_percentage * cart_item.product.price) / 100
            cart_item.product.offer_price = cart_item.product.price - discount_price
            total += (cart_item.product.offer_price * cart_item.quantity)
            quantity += cart_item.quantity
        else:
            total += (cart_item.product.price * cart_item.quantity)
            quantity += cart_item.quantity

    tax = (2 * total) / 100
    order_total = total
    grand_total = order_total + tax

    order_address = None

    if request.method == 'POST':

        order_address_id = request.POST.get('selected_address', None)

        data = Order()
        data.user = current_user
        data.order_total = order_total
        data.tax = tax
        data.ip = request.META.get('REMOTE_ADDR')
        data.save()

        if order_address_id:
            # Retrieve the address associated with the order
            order_address = Address.objects.get(id=order_address_id)
            data.address = order_address
            data.save()

        # #Generate Order Number:
        yr = int(date.today().strftime('%Y'))
        mt = int(date.today().strftime('%m'))
        dt = int(date.today().strftime('%d'))
        d = date(yr, mt, dt)
        current_date = d.strftime("%Y%m%d")
        order_number = current_date + str(data.id)
        data.order_number = order_number
        data.save()

        order = Order.objects.get(user=current_user, is_ordered=False, order_number=order_number)

        context = {
            'order_address': order_address,
            'order': order,
            'cart_items': cart_items,
            'tax': tax,
            'order_total': order_total,
            'grand_total': grand_total,
        }
        return redirect('orders:coupon', order_id=data.id)
        # return render(request, 'orders/place-order.html', context)
    else:
        return HttpResponse('Error!')


def coupon(request, order_id):
    coupons = Coupons.objects.all()
    user = request.user

    coupon_statuses = []

    for coupon in coupons:
        is_used = UserCoupons.objects.filter(coupon=coupon, user=user, is_used=True).exists()
        coupon_statuses.append("Used" if is_used else "Active")

    all_used = all(status == "Used" for status in coupon_statuses)

    if all_used:
        order = get_object_or_404(Order, id=order_id, user=user, is_ordered=False)
        context = {
            'order_address': order.address,
            'order': order,
            'cart_items': CartItem.objects.filter(user=user),
            'order_total': order.order_total,
            'tax': order.tax,
            'grand_total': order.order_total + order.tax,
            'wallet': user.wallet
        }
        return render(request, 'orders/place-order.html', context)
    else:
        order = get_object_or_404(Order, id=order_id, user=user, is_ordered=False)

        coupons = Coupons.objects.all()
        user = request.user

        coupon_statuses = []

        for coupon in coupons:
            is_used = UserCoupons.objects.filter(coupon=coupon, user=user, is_used=True).exists()
            coupon_statuses.append("Used" if is_used else "Active")

        coupon_data = zip(coupons, coupon_statuses)

        context = {
            'order_address': order.address,
            'order': order,
            'cart_items': CartItem.objects.filter(user=user),
            'order_total': order.order_total,
            'tax': order.tax,
            'grand_total': order.order_total + order.tax,
            'coupon_data': coupon_data,
        }
        return render(request, 'orders/apply-coupon.html', context)


def apply_coupon(request, order_id):
    if request.method == 'POST':
        coupon_code = request.POST.get('coupon_code')
        # request.session['coupon_code'] = coupon_code

        try:
            coupon = Coupons.objects.get(coupon_code=coupon_code)
            order = Order.objects.get(id=order_id)
            user = request.user

            if coupon.valid_from <= timezone.now() <= coupon.valid_to:
                if order.order_total >= coupon.minimum_amount:
                    if coupon.is_used_by_user(request.user):
                        messages.warning(request, 'Coupon has already been used')
                    else:
                        order.coupon_discount = coupon.discount
                        updated_total = order.order_total - float(coupon.discount)
                        order.order_total = updated_total
                        order.save()

                        used_coupons = UserCoupons(user=request.user, coupon=coupon, is_used=True)
                        used_coupons.save()

                        #Calculation of Total Product Discount
                        cart_items = CartItem.objects.filter(user=request.user, is_active=True)
                        product_discount = 0
                        for cart_item in cart_items:
                            if cart_item.product.offer_percentage > 0:
                                discount_price = (cart_item.product.offer_percentage * cart_item.product.price) / 100
                                product_discount += discount_price * cart_item.quantity

                        context = {
                            'coupon_discount': order.coupon_discount,
                            'order_id': order.id,
                            'order_address': order.address,
                            'order': order,
                            'cart_items': CartItem.objects.filter(user=user),
                            'order_total': order.order_total,
                            'tax': order.tax,
                            'grand_total': order.order_total + order.tax,
                            'product_discount': product_discount,
                            'total_discount': order.coupon_discount + product_discount,
                            'wallet': user.wallet,
                        }
                        return render(request, 'orders/place-order.html', context)
                else:
                    messages.warning(request, 'Coupon is not applicable for order total')
            else:
                messages.warning(request, 'Coupon is not applicable for the current date')
        except ObjectDoesNotExist:
            messages.warning(request, 'Coupon code is invalid')
            return render(request, 'orders/place-order.html', {'order_id': order_id})

    # Redirect to the place order page if the request method is not POST
    return render(request, 'orders/place-order.html', {'order_id': order_id})


def make_payments(request, order_id):
    current_user = request.user

    # Retrieve the order using the given order_id and user
    order = get_object_or_404(Order, id=order_id, user=current_user, is_ordered=False)

    if request.method == 'POST':
        if order and order.status == 'Pending':
            payment_method = request.POST.get('paymentMethod')

            # Perform different actions based on the selected payment method

EcomProject/templates/orders/apply-coupon.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="section-content padding-y bg">
    <div class="container">
        <!-- ============================ COMPONENT 1 ================================= -->
        <h4 class="text-center mb-10">Apply Coupon and Place Order</h4>
        <div class="row">
            <aside class="col-lg-4">
                {% include 'includes/alerts.html' %}
                <div class="card">
                    <div class="card-body">
                        <h5 class="text-center text-white bg-warning" style="border-radius: 8px; padding: 10px;"> Order
                            Summary </h5>
                        <dl class="dlist-align">
                            <dt>Total Price:</dt>
                            <dd class="text-right">Rs. {{ order_total | floatformat:2 }}</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Tax:</dt>
                            <dd class="text-right"> Rs. {{ tax | floatformat:2 }}</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Grand Total:</dt>
                            <dd class="text-right text-dark b"><strong>Rs. {{ grand_total | floatformat:2 }}</strong></dd>
                        </dl>
<!--                        <button type="submit" class="btn btn-primary btn-block">Place Order</button>-->
                        <!--Coupon Section-->
                        <div class="card">
                            <div class="card-body">
                                <form method="POST" action="{% url 'orders:apply_coupon' order_id=order.id %}">
                                    {% csrf_token %}
                                    <div class="coupon-section">
                                        <h6>Apply Coupon</h6>
                                        <div class="coupon-form-wrap">
                                            <p><input type="text" name="coupon_code" class="form-control" placeholder="Enter your Coupon Code"></p>
                                            <button type="submit" class="btn btn-primary">Apply Coupon and Place Order</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div> <!-- card-body.// -->
                </div> <!-- card.// -->
            </aside> <!-- col.// -->
            <main class="col-md-8">
                <article class="card">
                    <header class="card-header">
                        <strong class="d-inline-block mr-3">Coupon Details</strong>
                    </header>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th scope="col">Coupon Code</th>
                                            <th scope="col">Min. Purchase Amount</th>
                                            <th scope="col">Discount Amount</th>
                                            <th scope="col">Valid Till</th>
                                            <th scope="col">Status</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for coupon, status in coupon_data %}
                                        <tr>
                                            <td>{{ coupon.coupon_code }}</td>
                                            <td>{{ coupon.minimum_amount }}</td>
                                            <td>{{ coupon.discount }}</td>
                                            <td>{{ coupon.valid_to|date:"d-m-Y" }}</td>
                                            <td>{{ status }}</td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div> <!-- row.// -->
                    </div> <!-- card-body .// -->
                </article> <!-- order-group.// -->
            </main>
        </div> <!-- row.// -->
        <!-- ============================ COMPONENT 1 END .// ================================= -->
    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

{% endblock %}

EcomProject/templates/orders/order-confirmation.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="section-content padding-y bg">
        <div class="container">
            <div class="text-center">
                <h4>Your order has been confirmed!!!</h4>
                <p>Order Number: {{ order.order_number }}</p>
                <p>Payment ID: {{ order.payment }}</p>
                <a href="{% url 'store' %}" class="btn btn-primary">Continue Shopping</a>
            </div>
        </div>
    </section>


<div class="container" style="margin-top: 50px;">
    <center><i class="fas fa-check-circle" style="font-size: 72px;margin-bottom: 20px;color: #28A745;"></i></center>
    <h2 class="text-center">Payment Successful</h2>
	<br>
</div>


{% endblock %}

EcomProject/templates/orders/place-order.html
{% extends 'base.html' %}
{% load static %}

<script src="https://code.jquery.com/jquery-3.6.4.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.6.0/js/bootstrap.min.js"></script>


{% block content %}
<h4 class="text-center mb-0">Review your order and Make payment</h4>
<section class="section-content padding-y bg">
    <div class="container">
        <!-- ============================ COMPONENT 1 ================================= -->
        <div class="row">
            <aside class="col-md-8 mx-auto">
                <div class="card">
                    <form action="{% url 'orders:make_payments' order_id=order.id %}" method="POST">
                        {% csrf_token %}
                        <h5 class="card-header text-center">Billing Address</h5>
                        <div class="card-body">
                            <p class="card-text mb-0">{{ order_address.full_name }}</p>
                            <p class="card-text mb-0">{{ order_address.full_address }}</p>
                            <p class="card-text mb-0">{{ order_address.city }}, {{ order_address.state }}</p>
                            <p class="card-text mb-0">{{ order_address.country }}</p>
                            <p class="card-text mb-0">{{ order_address.phone_number }}</p>
                        </div>
                </div>
                <div class="card">
                    <h5 class="card-header text-center">Product Reviews</h5>
                    <div class="card-body">
                        <p class="card-text"></p>
                        <table class="table table-borderless table-shopping-cart">
                            <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for cart_item in cart_items %}
                            <tr>
                                <td>
                                    <figure class="itemside align-items-center">
                                        <div class="aside"><img src="{{ cart_item.product.product_image.url }}"
                                                                class="img-sm">
                                        </div>
                                        <figcaption class="info">
                                            <a href="{{ cart_item.product.get_url }}" class="title text-dark">
                                                {{ cart_item.product.product_name }}</a>
                                            <p class="text-muted small">
                                                {% if cart_item.variant.all %}
                                                    {% for item in cart_item.variant.all %}
                                                        {{ item.variant_category | capfirst }}: {{ item.variant_value | capfirst }} <br>
                                                    {% endfor %}
                                                {% endif %}
                                            </p>
                                        </figcaption>
                                    </figure>
                                </td>
                                <td>
                                    <label>{{ cart_item.quantity }}</label>
                                </td>
                                <td>
                                    {% if cart_item.product.offer_percentage > 0 %}
                                        <div class="price-wrap">
                                            <var class="price">₹ {{ cart_item.sub_total_offer }} </var>
                                            <small class="text-muted"> ₹ {{ cart_item.product.offer_price }} each </small>
                                        </div> <!-- price-wrap .// -->
                                    {% else %}
                                        <div class="price-wrap">
                                            <var class="price">₹ {{ cart_item.sub_total }} </var>
                                            <small class="text-muted"> ₹ {{ cart_item.product.price }} each </small>
                                        </div> <!-- price-wrap .// -->
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </aside> <!-- col.// -->
            <aside class="col-md-3 mx-auto">
                <div class="card">
                    <div class="card-body">
                        <h5 class="text-center text-white bg-warning" style="border-radius: 8px; padding: 10px;"> Order
                            Summary </h5>
                        <dl class="dlist-align">
                            <dt>Sub Total:</dt>
                            <dd class="text-right">₹  {{ order_total | floatformat:2 }}</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Tax:</dt>
                            <dd class="text-right"> ₹ {{ tax | floatformat:2 }}</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Grand Total:</dt>
                            <dd class="text-right text-dark b"><strong>₹ {{ grand_total | floatformat:2 }}</strong></dd>
                        </dl>
                        {% if coupon_discount > 0 and product_discount > 0 %}
                            <hr>
                            <br>
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="discountDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                You have saved! <strong>₹ {{ total_discount | floatformat:2 }}</strong>
                            </button>
                            <br>
                            <div class="dropdown-menu" aria-labelledby="discountDropdown">
                                <a class="dropdown-item" href="#">Coupon Discount: ₹{{ coupon_discount | floatformat:2 }}</a>
                                <a class="dropdown-item" href="#">Product Discount: ₹{{ product_discount | floatformat:2 }}</a>
                            </div>
                        {% elif coupon_discount > 0 %}
                            <hr>
                            <p class="text-center">You have saved! <strong>₹ {{ coupon_discount | floatformat:2 }}</strong></p>
                        {% elif product_discount > 0 %}
                            <hr>
                            <p class="text-center">You have saved! <strong>₹ {{ product_discount | floatformat:2 }}</strong></p>
                        {% endif %}
                        <h5 class="text-center text-white bg-warning" style="border-radius: 8px; padding: 10px;">Select
                            Payment Method</h5>
                        <dl class="dlist-align">
                            <dt><input type="radio" name="paymentMethod" value="CashOnDelivery" required> Wallet </dt>
                            <dd class="text-right">{{ wallet | floatformat:2 }}</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt><input type="radio" name="paymentMethod" value="CashOnDelivery"> Cash On
                                Delivery
                            </dt>
                            <dd class="text-right"></dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt><input type="radio" name="paymentMethod" value="PayPal"> PayPal</dt>
                            <dd class="text-right"></dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt><input type="radio" name="paymentMethod"> Debit/Credit Card</dt>
                            <dd class="text-right"></dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt><input type="radio" name="paymentMethod"> UPI Payment</dt>
                            <dd class="text-right"></dd>
                        </dl>
                        <button type="submit" class="btn btn-primary btn-block">Place Order</button>
                        </form>
                    </div> <!-- card-body.// -->
                </div> <!-- card.// -->
            </aside> <!-- col.// -->
        </div> <!-- row.// -->
        <!-- ============================ COMPONENT 1 END .// ================================= -->
    </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT END// ========================= -->

<script>
    $(document).ready(function () {
        // Close dropdown on click outside
        $(document).click(function (event) {
            var clickover = $(event.target);
            var $navbar = $(".navbar-collapse");
            var _opened = $navbar.hasClass("in");
            if (_opened === true && !clickover.hasClass("navbar-toggle")) {
                $navbar.collapse('hide');
            }
        });

        // Prevent dropdown menu from closing on click inside
        $(".dropdown-menu").click(function (e) {
            e.stopPropagation();
        });
    });
</script>

{% endblock %}